validate whether gnupg has allow-loopback-pinentry

diff --git a/sign-packages/commands/setup-env.yml b/sign-packages/commands/setup-env.yml
--- a/sign-packages/commands/setup-env.yml
+++ b/sign-packages/commands/setup-env.yml
@@ -14,6 +14,10 @@ steps:
           echo "ERROR: you must set \$GPG_SECRET_KEY with the Base64-encoded contents of your GPG secret key"
           exit 1
         fi
+        if [ `gpg-agent --help | grep -c allow-loopback-pinentry` -eq 0 ]; then
+          echo "ERROR: GnuPG 2.1 or higher is required"
+          exit 1
+        fi
         export GNUPGHOME="$HOME/.gnupg"
         eval $(gpg-agent --daemon --allow-loopback-pinentry)
         install -d -m 700 "$GNUPGHOME"
